name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  test: # names the job
    runs-on: ubuntu-latest # sets the version of linux we want to use, should be what you have on your server
    environment:
      name: qwirkle
    strategy:
      fail-fast: false # tells github to not run further steps if this one fails
      matrix:
        node-version: [14.x] # sets the version of node we want to use, should be what you have on your server

    steps:
      - uses: actions/checkout@v2 # fetches your commit to test it
      - name: Use Node.js ${{ matrix.node-version }} # names our step
        uses: actions/setup-node@v1 # downloads node and npm
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test # builds your app

        env:
          CI: true
      - uses: actions/checkout@v2
      - name: Build dist angular
        working-directory: ./dist
        run: |
          npm ci
          npm run build


      - name: Archive build

        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          source: './dist'
          target: '~/var/www/qwirkle/frontend/'
          strip_components: 1
